# Generated by Django 3.0.6 on 2020-06-01 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 6, 1, 8, 11, 0, 624936, tzinfo=utc))),
                ('author', models.CharField(max_length=32)),
                ('redirect_access', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
